const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const ROOT = path.resolve(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(ROOT, file), 'utf8')

test('recipe list exposes the beta AI naming entry above search', () => {
  const wxml = read('miniprogram/pages/recipes/index.wxml')
  assert.ok(wxml.indexOf('ai-naming-banner') < wxml.indexOf('search-box'))
  assert.match(wxml, /体验版/)
  assert.match(read('miniprogram/pages/recipes/index.js'), /onOpenMusicNaming/)
})

test('music naming page collects local settings and shows import progress', () => {
  const app = JSON.parse(read('miniprogram/app.json'))
  assert.ok(app.pages.includes('pages/music-naming/index'))
  const wxml = read('miniprogram/pages/music-naming/index.wxml')
  for (const label of ['DeepSeek API Key', '模型名称', '导入歌曲数量', '已完成', '解析失败']) assert.match(wxml, new RegExp(label))
})

test('checking NetEase login always gives visible progress and a result', () => {
  const js = read('miniprogram/pages/music-naming/index.js')
  const wxml = read('miniprogram/pages/music-naming/index.wxml')
  assert.match(js, /checkingLogin:\s*false/)
  assert.match(js, /正在检查网易云登录状态/)
  assert.match(js, /暂未检测到登录/)
  assert.match(js, /检查网易云登录状态失败/)
  assert.doesNotMatch(js, /catch\s*\(_\)\s*\{\s*\}/)
  assert.match(wxml, /loading="\{\{checkingLogin\}\}"/)
  assert.match(wxml, /disabled="\{\{checkingLogin \|\| loadingLogin\}\}"/)
  assert.match(wxml, /\{\{checkingLogin \? '检查中…' : '检查登录'\}\}/)
})

test('music assistant deployment allows one lyric and model call to finish', () => {
  const functionConfig = JSON.parse(read('cloudfunctions/musicAssistant/config.json'))
  const cloudbaseConfig = JSON.parse(read('cloudbaserc.json'))
  const deployment = cloudbaseConfig.functions.find((item) => item.name === 'musicAssistant')
  assert.ok(functionConfig.timeout >= 120)
  assert.ok(deployment)
  assert.ok(deployment.timeout >= 120)
})

test('music analysis has a cloud timer fallback and page exit only stops local work', () => {
  const config = JSON.parse(read('cloudfunctions/musicAssistant/config.json'))
  const timer = (config.triggers || []).find((item) => item.type === 'timer')
  const index = read('cloudfunctions/musicAssistant/index.js')
  const page = read('miniprogram/pages/music-naming/index.js')

  assert.ok(timer)
  assert.match(index, /event\.Type\s*===\s*['"]Timer['"]/)
  assert.match(index, /runBackground/)
  assert.match(page, /startJob\(\{[^}]*apiKey:\s*settings\.apiKey/s)
  assert.match(page, /onHide\(\)[\s\S]*this\._active\s*=\s*false/)
  assert.match(page, /onUnload\(\)[\s\S]*this\._active\s*=\s*false/)
  assert.match(page, /setInterval[\s\S]*refreshStatus/)
  assert.match(read('miniprogram/pages/music-naming/index.wxml'), /退出.*云端仍会继续解析/)
})

test('recipe editor offers AI naming beside the name and renders recommendation reasons', () => {
  const wxml = read('miniprogram/pages/recipe-edit/index.wxml')
  const wxss = read('miniprogram/pages/recipe-edit/index.wxss')
  assert.match(wxml, /class="name-row"[\s\S]*bindtap="onOpenAiNaming"/)
  assert.match(wxml, /酒的颜色/)
  assert.match(wxml, /起名偏好/)
  assert.doesNotMatch(wxml, /酒的颜色（选填）|起名偏好（选填）/)
  assert.doesNotMatch(wxml, /placeholder="例如[^"]*"/)
  assert.match(wxml, /<button size="mini" class="ai-close"[^>]*aria-label="关闭">\u00d7<\/button>/)
  assert.match(wxss, /\.ai-close\s*\{[^}]*width:\s*64rpx[^}]*height:\s*64rpx[^}]*min-height:\s*64rpx/s)
  assert.match(wxss, /\.ai-generate\s*\{[^}]*width:\s*240rpx[^}]*height:\s*64rpx[^}]*min-height:\s*64rpx/s)
  assert.match(wxss, /\.ai-results\s*\{[^}]*width:\s*100%/s)
  assert.match(wxml, /<view wx:for="\{\{aiRecommendations\}\}"[^>]*class="ai-result"[^>]*aria-role="button"/)
  assert.doesNotMatch(wxml, /<button wx:for="\{\{aiRecommendations\}\}"[^>]*class="ai-result"/)
  assert.match(wxml, /\{\{item\.recommended_name\}\}[\s\S]*\{\{item\.artist\}\}/)
  assert.match(wxml, /data-song-id="\{\{item\.song_id\}\}"/)
  assert.match(wxml, /\{\{item\.reason\}\}/)
})

test('recipe detail opens a compact explanation window from the music naming mark', () => {
  const wxml = read('miniprogram/pages/recipe-detail/index.wxml')
  const wxss = read('miniprogram/pages/recipe-detail/index.wxss')
  const js = read('miniprogram/pages/recipe-detail/index.js')
  assert.match(wxml, /wx:if="\{\{detail\.hasMusicNaming\}\}"[\s\S]*music-naming-mark[\s\S]*bindtap="onOpenMusicReason"/)
  assert.doesNotMatch(wxml, /<button[^>]*class="music-naming-mark"/)
  assert.match(wxml, /src="\/assets\/music-naming-star\.png"/)
  assert.match(wxml, /music-naming-fallback/)
  assert.match(wxml, /music-reason-mask[\s\S]*\{\{detail\.musicNaming\.reason\}\}/)
  assert.doesNotMatch(wxml, /music-reason-close|选这首歌的原因/)
  assert.match(wxss, /\.music-naming-mark\s*\{[^}]*width:\s*50rpx;[^}]*height:\s*50rpx;[^}]*overflow:\s*hidden/s)
  assert.match(wxss, /\.music-naming-logo\s*\{[^}]*transform:\s*scale\(2\.2\)/s)
  assert.match(wxss, /\.music-reason-window\s*\{[^}]*background:\s*#242321/s)
  assert.match(wxss, /\.music-reason-title\s*\{[^}]*color:\s*#ffffff/s)
  assert.match(wxss, /\.music-reason-copy\s*\{[^}]*color:\s*#ffffff/s)
  assert.match(wxss, /\.music-reason-copy\s*\{[^}]*font-size:\s*22rpx/s)
  assert.match(js, /onOpenMusicReason/)
  assert.match(js, /onCloseMusicReason/)
})
